# Generated by Django 5.1.2 on 2024-11-11 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Exam Title')),
                ('pass_percentage', models.PositiveIntegerField(verbose_name='Pass Percentage')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('test_count', models.PositiveIntegerField(verbose_name='Number of Tests')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='ExamStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Not Passed', max_length=16, verbose_name='Status')),
                ('total_score', models.FloatField(default=0, verbose_name='Total Score')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Exam Student',
                'verbose_name_plural': 'Exam Students',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='users',
            field=models.ManyToManyField(through='exam.ExamStudents', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.CreateModel(
            name='ExamTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Exam')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Exam Test',
                'verbose_name_plural': 'Exam Tests',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentExamTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct_answer', models.BooleanField(blank=True, null=True, verbose_name='Is Correct Answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.exam', verbose_name='Exam')),
                ('selected_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tests.testquestion', verbose_name='Selected Answer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Student Exam Test Answer',
                'verbose_name_plural': 'Student Exam Test Answers',
            },
        ),
    ]
